services:
  dive-app:
    image: spyminer/abyss-deco-planner:latest
    container_name: abyss
    ports:
      - "8080:8080"
    volumes:
      - dive-data:/app/server/data
    restart: unless-stopped

volumes:
  dive-data:
